oysterprotocol/brokernode

DataMap.php

I want to merge the datamap and database files so Aaron isn't using an old file and doesn't redo my work.

Andrew dev

---

broker-node/app/DataMapping.php
broker-node/app/Http/Controllers/UploadSessionController.php
broker-node/app/UploadSession.php
broker-node/composer.json
broker-node/composer.lock
broker-node/database/migrations/2018_01_09_020333_create_data_mappings_table.php
broker-node/database/migrations/2018_01_09_024930_create_upload_sessions_table.php

- Updates model schema w/ indexes
- Index on composite key (genesis_hash, chunk_idx)
- Stores files_size_bytes as BigInteger to handle large files
- Uses UUID to handle distributed nature of IDs
- Receives genesis hash as parameter
- Saves session in DB

Create upload session endpoint v1 complete

---

broker-node/app/DataMapping.php
broker-node/app/Http/Controllers/UploadSessionController.php
broker-node/routes/api.php

- Creates datamap when a session is started
- This is synchronous for now to avoid dealing with potential race conditions
- Implements /api/v1/upload-session endpoint to upload chunks

Endpoint for uploading chunks

---

broker-node/app/DataMapping.php
broker-node/app/Http/Controllers/UploadSessionController.php
broker-node/database/migrations/2018_01_09_020333_create_data_mappings_table.php
broker-node/database/migrations/2018_01_09_020333_create_data_maps_table.php
broker-node/routes/api.php

- Adds status field to data_maps table
- Adds endpoint to poll for a chunk's status
- Diff is a little noisy because DataMapping is renamed to DataMap

Chunk polling endpoint

---

broker-node/app/Clients/BrokerNode.php
broker-node/app/Http/Controllers/UploadSessionController.php
broker-node/app/UploadSession.php

Issues:  
**41	Put the ethereum address and payment amount owed in a packet and set as the return value for the initialize upload api call**
**39	Build the Function To Calculate The Required Payment Amount**
**Description:**
1 PRL / GB 
We hardcode this for the test net.
So take the filesize and calculate the amount of PRL owed.
The function is passed a file size

payment related changes

---

broker-node/app/Console/Commands/CheckChunkStatus.php

Fix Sentry error https://sentry.io/oyster-pearl/oyster/issues/442613539/

Fix Sentry error

---

broker-node/app/Clients/BrokerNode.php
broker-node/app/Clients/requests/IriData.php

Rfornea patch 1

---

broker-node/app/Clients/iota-php-port/PrepareTransfers.php
broker-node/app/Clients/requests/IriData.php

Prepare transfers fixes

---

broker-node/app/Http/Controllers/UploadSessionController.php
broker-node/database/migrations/2018_01_09_020333_create_data_maps_table.php

1. Increase size limit of message field on data_maps table
2. Delete chunk field on data_maps (will just use the message field)

Fix msg size limit

---

broker-node/app/ChunkEvents.php
broker-node/app/Clients/BrokerNode.php
broker-node/database/migrations/2018_02_05_200133_create_chunk_events_table.php

Trying to integrate basic event logging.

Another test of git vm integration

---

broker-node/app/Clients/BrokerNode.php
broker-node/app/Clients/requests/IriData.php

Reducing spamming, increasing depth.  
Didn't cut out all spamming, because we still need proper hooknode selection.

Rfornea patch 8

---

broker-node/app/Http/Controllers/UploadSessionController.php

[WIP] Please do not merge yet!

Beta broker

---

jobs/job_runner.go
jobs/process_unassigned_chunks.go
jobs/purge_completed_sessions.go
jobs/purge_completed_sessions_test.go
migrations/20180320145525_create_completed_data_maps.down.fizz
migrations/20180320145525_create_completed_data_maps.up.fizz
models/completed_data_maps.go

-Adds "PurgeCompletedSessions" job and tests
-Moves completed data maps to a completed_data_maps table.  Will need this if we decide we care about confirmation rates, though we might not care anymore
-Deletes completed sessions

Adds "purgeCompletedSessions" job

---

jobs/flush_old_webnodes.go
jobs/flush_old_webnodes_test.go
migrations/20180320195313_create_webnodes.down.fizz
migrations/20180320195313_create_webnodes.up.fizz
models/completed_data_maps_test.go
models/data_maps.go
models/models_test.go
models/upload_sessions.go
models/webnodes.go
models/webnodes_test.go

-adds "FlushOldWebnodes"
-adds a database for webnodes
-had to do some weird sleep thing in the tests.  You're supposed to be able to manually set updated_at with Exec statements.  I tried several things and was unsuccessful.

Adds a database for webnodes and a job "FlushOldWebnodes"

---

jobs/purge_completed_sessions_test.go
jobs/update_timed_out_data_maps_test.go
jobs/verify_data_maps_test.go
models/data_maps.go

We already get `math.Ceil`, so we don't need to use `<=` in the for loop.

Creates an extra chunk

---

migrations/20180406142836_create_brokernodes.down.fizz
migrations/20180406142836_create_brokernodes.up.fizz
models/brokernode.go
models/brokernode_test.go

Required for "purchasing a broker node address that the web node does not have already"
https://docs.google.com/document/d/1FCS_55lhRd539xl2FEQuIZvzxQDslGhWPsPBEUDLtEk/edit

Creates brokernode model

---

actions/app.go
actions/transaction_brokernodes.go
jobs/job_runner.go
models/transaction.go

Verify PoW sent from the webnode
Reference: https://docs.google.com/document/d/1FCS_55lhRd539xl2FEQuIZvzxQDslGhWPsPBEUDLtEk/edit

Verify PoW for broker node address purchase

---

actions/upload_sessions.go
docker-compose.yml
jobs/purge_completed_sessions_test.go
migrations/20180313231024_create_data_maps.up.fizz
migrations/20180316183149_create_upload_sessions.up.fizz
models/upload_sessions.go

Had to switch to mariaDB in order to use JSON in a column.

Db for prl 201

---

actions/app.go
actions/transaction_brokernodes.go
actions/transaction_genesis_hashes.go
jobs/job_runner.go
migrations/20180313231024_create_data_maps.up.fizz
migrations/20180321020504_create_stored_genesis_hashes.up.fizz
models/data_maps.go
models/stored_genesis_hashes.go

Reference: https://docs.google.com/document/d/1KtkToH7pU22Qi3b27pMOzPyaiXi14FXx690dJ5TYBIs/edit

API for purchasing genesis hashes

---

models/data_maps.go
models/upload_sessions.go
utils/db_utils.go
utils/db_utils_test.go
utils/test_utils.go
utils/utils.go
utils/utils_test.go

Have a better way to convert a struct{} data with db tag into string format for update a table

Create a batch update to data_maps table

---

.gitignore
actions/treasures.go
models/data_maps.go

build datamap
prepared cycle for checking IOTA 
checking epoch

treasure hunting 

---

actions/actions_test.go
actions/treasures.go
actions/treasures_test.go
actions/upload_sessions.go
jobs/job_runner_test.go
jobs/update_timed_out_data_maps.go
jobs/verify_data_maps.go
models/models_test.go
models/upload_sessions_test.go
services/iota_wrappers.go
utils/mode.go
utils/segment_logger.go

Fixes those errors that were coming from actions/treasures.go and actions/upload_sessions.go

Upload sessions error

---

actions/upload_sessions.go
jobs/claim_unused_prls.go
jobs/claim_unused_prls_test.go
jobs/flush_old_webnodes.go
jobs/process_paid_sessions.go
jobs/process_unassigned_chunks.go
jobs/purge_completed_sessions.go
jobs/update_timed_out_data_maps.go
migrations/20180313231024_create_data_maps.up.fizz
models/data_maps.go
services/eth_gateway.go
services/eth_gateway_mock.go
services/iota_wrappers.go

-Segment logs everything.  
-Fixes a small error in actions/upload_sessions.go that was causing the data_maps array to not get populated.  There may be different ways we can approach this, if the way I have fixed it is not suitable.  
https://gophers.slack.com/archives/C3MSAFD40/p1525467579000325

fix upload_sessions error in batch updates, log every event.

---

actions/treasures.go
actions/treasures_test.go
services/eth_gateway.go

Change stringToAddress(private) to StringToAddress(public).
And run "go fmt" to reform files.

Call Claim method in the treasure.go

---

services/eth_gateway.go

In A few places we did not handle err at all and we return nil object from sharedClient() method.
This will lead to panic due to nil object.

Better handling error case in EthGateway

---

actions/transaction_brokernodes.go
actions/upload_sessions.go
jobs/flush_old_webnodes.go
jobs/process_paid_sessions.go
models/completed_uploads.go
models/data_maps.go
models/upload_sessions.go
services/eth_gateway.go
utils/db_utils.go
utils/trytes_conversion.go
utils/utils.go

When we received error, only do raven logging if it is a third party APIs. If we call our own method, then don't log anything since upstream method should log it.
Also, convert += to append string to strings.Builder approach

Add Raven logging for errors

---

models/upload_sessions.go
models/upload_sessions_test.go

-Properly calculates the PRL invoice
-Adds unit tests

Update how storage cost is calculated

---

actions/upload_sessions.go

Adds a check to waitForTransferAndNotifyBeta that will not wait for the transfer unless the broker is in PROD_MODE

Don't wait if not in PROD_MODE

---

grifts/db.go
jobs/process_paid_sessions.go
jobs/process_paid_sessions_test.go
jobs/process_unassigned_chunks.go
jobs/process_unassigned_chunks_test.go
migrations/20180522214131_create_treasures.down.fizz
migrations/20180522214131_create_treasures.up.fizz
models/data_maps_test.go
models/treasure.go
models/treasure_test.go
models/upload_sessions.go
models/upload_sessions_test.go
services/eth_gateway.go

-adds treasure addresses to a db table when we need to send treasures to them
-adds WIP methods to process_paid_sessions to send treasures to those addresses.  Need to sync up with Astor and tweak these methods to make sure they work
Wanting to fix these methods up a little more and add some more tests in next PR.  This PR was already getting pretty big.

Preliminary db table, cron task, and methods to send the PRLs to the treasure addresses

---

jobs/process_paid_sessions.go
jobs/process_unassigned_chunks.go
migrations/20180522214131_create_treasures.up.fizz
models/treasure.go
models/treasure_test.go

-adds send gas method
-adds method to invoke bury
-adds eth key to treasures struct, will need this for burying
All still WIP.

send gas, bury prl, add eth key to treasures struct

---

services/eth_gateway.go

If balance is there, then don't need to wait further for the transfer

Check balance first before wait for Transfer

---

jobs/remove_unpaid_upload_session_test.go
services/eth_gateway.go

Anyone who is QAing will need this change.

eth node URL wasn't properly defined (don't delete this branch)

---

models/upload_sessions.go
models/upload_sessions_test.go
services/eth_gateway.go
services/iota_wrappers.go

-Fix amount of PRL to bury
-Point to live smart contract (NOTE:  anyone still using the testnet will need to not use this change)
-Fix directory path to key.prv

Intermittent QA changes

---

jobs/flush_old_webnodes.go
jobs/job_runner.go
jobs/process_paid_sessions.go
jobs/process_unassigned_chunks.go
jobs/purge_completed_sessions.go
jobs/remove_unpaid_upload_session.go
jobs/update_timed_out_data_maps.go
jobs/verify_data_maps.go
models/treasure.go
models/upload_sessions.go
services/eth_gateway.go
utils/utils.go

Besides tags, which is indexed. Additional info is not indexed and it is on the bottom of the sentry.io log.
It provides additional info about the error, like what is the input, expected output, running condition.
This value is completely freeform.
Ex:
extraInfo["input"] = 100
extraInfo["output"] = "hello world"

Provide additional info for Raven sentry logging

---

jobs/process_paid_sessions.go
jobs/process_unassigned_chunks.go
jobs/purge_completed_sessions.go
utils/utils.go

Note: this will create in-memory struct even the error is nil. Probably no the best case, however, I am going to opt it next round

Add additional info to sentry.io logs

---

actions/transaction_brokernodes.go
actions/transaction_genesis_hashes.go
actions/upload_sessions_test.go
models/stored_genesis_hashes.go
services/iota_wrappers.go

-get oldest chunk for webnode, instead of trying to get chunks whose genesis hashes match the stored_genesis_hash (this won't work)
-comment out flaky test

QA fixes associated with webnode testing

---

docker-compose.yml
main.go
services/kv_store.go
services/kv_store_test.go

Deprecating Message field in a separate PR since this one was getting pretty big

Badger as a service

---

services/kv_store_test.go
utils/db_utils_test.go
utils/segment_logger_test.go
utils/test_utils.go
utils/utils_test.go

All unit test should be *_test package.
Export Assert method so that other package could use it.

Clean util dir

---

actions/upload_sessions.go
services/kv_store.go

By default, disable this feature

Add KVStore batch set in the upload session

---

actions/upload_sessions.go
migrations/20180608213539_add_msg_id_to_deprecate_msg.down.fizz
migrations/20180608213539_add_msg_id_to_deprecate_msg.up.fizz
models/completed_data_maps.go
models/data_maps.go
models/data_maps_test.go
models/treasure.go
services/kv_store.go
services/kv_store_test.go

WARNING: Don't merge this yet. Still a WIP.

[WIP] Deprecate msg

---

jobs/badger_db_gc.go
jobs/job_runner.go
services/kv_store.go

Need to run background job to reduce BadgerDB footprint and compact its memory usage.

Add GC for BadgerDB

---

actions/transaction_brokernodes.go
grifts/db.go

-more detailed error
-some more grifts to use while QAing

better error, add more grifts

---

actions/upload_sessions.go
services/kv_store.go
services/kv_store_test.go

More testing and more fixed on migration to BadgerDB

More fixed on Message field

---

models/data_maps.go
models/upload_sessions.go
utils/db_utils.go

See here for deadlock:
https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans
Solution:
1) Adding retry logic
2) Use select method to create a temp table and then update based on that temp table only.

Adding retry logic to try it best to avoid Deadlock

---

models/data_maps.go
models/upload_sessions.go

Use MsgStatus as way to improve performance of SQL query. Otherwise, we need to cross query.
TODO: assign Uploaded value in the upcoming PR

Add MsgStatus

---

migrations/20180321020504_create_stored_genesis_hashes.up.fizz
migrations/20180625135525_add_treasure_status_to_stored_genesis_hashes.up.fizz

This column addition should have been in its own file

Treasure status column addition should be in its own file

---

jobs/claim_unused_prls.go
utils/utils.go

Already logged it. This will prevent dup entry in sentry.io

Remove duplicate logging

---

jobs/bury_treasure_addresses.go
services/eth_gateway.go
services/eth_gateway_test.go
services/prometheus.go

Some of the code climates issues resolved.

Codeclimate

---

actions/upload_sessions.go
actions/upload_sessions_test.go
models/models_test.go
utils/utils.go
utils/utils_test.go

Fixed msgStatus is not written into db

---

actions/treasures.go
actions/treasures_test.go
actions/upload_sessions.go
grifts/db.go
jobs/process_unassigned_chunks.go
jobs/process_unassigned_chunks_test.go
jobs/purge_completed_sessions.go
jobs/purge_completed_sessions_test.go
jobs/remove_unpaid_upload_session.go
models/data_maps.go
models/stored_genesis_hashes.go
services/iota_wrappers.go
services/kv_store.go
utils/mode.go

This PR pulls out a good chunk of the changes from a different PR, so that the other PR won't be so huge and hard to look at.
-fixes small errors and typos
-add more grifts
-guard against adding certain things to the database in test modes
-updates to model files
-fix a few places where a model was missing a property or a model was being created too early.

Add modes, grifts, guard against test mode, fix small errors and typos

---

.travis.yml

cd back to original directory after cypress tests
@rfornea im hoping this fixes the issue, but i cant test cause its part of the deploy, can you approve please? We will see what it can do.

Fixed broken deploy

---

actions/upload_sessions.go
actions/upload_sessions_test.go
jobs/process_paid_sessions.go
jobs/process_paid_sessions_test.go
jobs/purge_completed_sessions.go
models/data_maps.go
models/data_maps_test.go
models/upload_sessions.go
services/kv_store.go
utils/trytes_conversion.go

(Note: we have not launched BadgerDB. So there is not need to worry about data inside BadgerDB is not encoded. Since we will wipe it out in releases.)

Avoid encoding the message data before BadgerDB

---

actions/transaction_brokernodes.go
actions/transaction_genesis_hashes.go
grifts/db.go
jobs/process_unassigned_chunks_test.go
models/broker_broker_transactions_test.go
models/data_maps.go
models/data_maps_test.go
models/stored_genesis_hashes.go
models/upload_sessions.go
models/upload_sessions_test.go
services/eth_gateway.go
services/iota_wrappers.go

Small things that came up while QAing

Pre deploy qa

---

jobs/bury_treasure_addresses.go
jobs/bury_treasure_addresses_test.go
jobs/job_runner.go
jobs/purge_completed_sessions.go
jobs/store_completed_genesis_hashes.go
jobs/store_completed_genesis_hashes_test.go
migrations/20180719012045_add_unique_constraints.down.sql
migrations/20180719012045_add_unique_constraints.up.sql
models/stored_genesis_hashes.go
models/stored_genesis_hashes_test.go
services/prometheus.go

-adds a mutex to purge_completed_sessions
-runs the job less often
-does an additional check to avoid dupes

reduce frequency of job, add mutex

---

actions/upload_sessions.go
jobs/badger_db_gc_test.go
jobs/process_paid_sessions.go
jobs/process_paid_sessions_test.go
jobs/purge_completed_sessions.go
jobs/update_msg_status_test.go
models/completed_data_maps.go
models/data_maps.go
models/data_maps_test.go
models/models.go
models/models_test.go
services/kv_store.go
services/kv_store_test.go

-Sets TTL for all badger data
-Adds a test to make sure it works like you would think it would

TTL for all badger K:V pairs

---

actions/transaction_brokernodes.go
actions/transaction_genesis_hashes.go
actions/upload_sessions.go
actions/webnodes.go
jobs/job_runner.go
services/iota_wrappers.go

-add tangle maintenance env variabe
-check num_chunks_limit with each new upload so we don't have to rebuild the container for these changes to take effect
-lower mwm

add tangle_maintenance .env variable

---

jobs/job_runner.go
services/iota_wrappers.go

adjustments for private tangle

tangle adjustments

---

jobs/update_msg_status.go
jobs/update_msg_status_test.go
models/data_maps.go
models/models_utils.go
models/models_utils_test.go
utils/db_utils.go
utils/db_utils_test.go

This is prep for completed_data_map section

Clean up the DBUpsert method

---

jobs/process_paid_sessions.go
jobs/process_unassigned_chunks.go
jobs/purge_completed_sessions.go
jobs/remove_unpaid_upload_session.go
jobs/store_completed_genesis_hashes.go
jobs/update_msg_status.go
jobs/update_timed_out_data_maps.go
jobs/verify_data_maps.go
models/upload_sessions.go

We've had some errors with sql lately.  This is to help find where they are coming from while watching the brokers.

More detailed logging, to more easily find location of mysql errors

---

models/completed_uploads.go

Add more debug info

---

actions/upload_sessions.go

In one of our error, we did not check the validation error and pass the FileSizeInByte as 0 to Beta. In this case, just result an error the client

Check the validation error before calling to Beta

---

.buffalo.dev.yml
grifts/db.go

-adds a new grifts
-will rebuild if a grift file is changed

add new grift, rebuild on grift change

---

services/eth_gateway.go

Prefer to crash the app if Main Wallet key is invalid

Force releaser to check Main Wallet Key for Prod release

---

actions/app.go
grifts/db.go
jobs/check_all_data_is_ready.go
jobs/check_all_data_is_ready_test.go
jobs/job_runner.go
jobs/process_paid_sessions_test.go
jobs/process_unassigned_chunks.go
jobs/process_unassigned_chunks_test.go
jobs/verify_data_maps.go
jobs/verify_data_maps_test.go
main.go
models/upload_sessions.go
models/upload_sessions_test.go
utils/kv_store.go
utils/stack_impact_profiler.go

Adds memory profiler and fixes some errors that came up during QA

Memory profile and QA Fixes

---

models/broker_broker_transactions.go
models/completed_uploads.go
models/webnode_treasure_claims.go
utils/kv_store.go

-If the error is "resource temporarily unavailable", retry.  
-update all encryption to deal with aurora truncation

Badger error

---

jobs/check_all_data_is_ready.go
utils/kv_store.go

-remove some duplicated code (this could be part of the reason for the badger errors)
-increase number of retries before erroring in kv_store

Badger fixes

---

actions/app.go
actions/v2/upload_sessions.go
actions/v2/upload_sessions_test.go
actions/v3/actions.go
actions/v3/upload_sessions.go
utils/kv_store.go

- Namespaces V2 to add support for V3
- Internals of the PUT endpoint are just copied over from V2 for now

Sets up V3 of upload sessions API

---

jobs/check_all_data_is_ready.go
utils/kv_store.go

We have a couple ways to deal with concurrency. And we should reduce the error rate since we have retry logic.

Update KVStore to reduce error rate

---

actions/app.go
actions/utils/setup_app.go
actions/v2/actions.go
actions/v3/actions.go
actions/v3/actions_test.go

Configure app to be shared within v2 and v3

---

actions/v3/s3_utils.go
actions/v3/s3_utils_test.go
actions/v3/upload_sessions.go
jobs/attach_treasure.go
jobs/attach_treasure_test.go
jobs/bury_treasure_addresses.go
jobs/bury_treasure_addresses_test.go
jobs/job_runner_test.go
models/treasure.go
models/treasure_test.go
models/upload_sessions.go
models/upload_sessions_test.go
services/iota_wrappers.go
services/prometheus.go

Format object key as GenesisHash/fileIndex. Store data into S3.
Expect client to send data in batch of pre-defined the size. And Expect client to send data in the order.
Example:
Index as {1,2,3,4,5} is acceptable while {1,100,2, 101,3,102} is unacceptable.

Update V3 Update method to store data into S3 object

---

actions/v3/s3_utils.go
actions/v3/s3_utils_test.go

Add list prefix method for getting the ObjectKey

S3: List Prefix for ObjectKey

---

actions/app.go
actions/status.go
actions/status_test.go

-adds numChunksLimit to status response
-return -1 if there is no limit

include numChunksLimit in status response

---

actions/v2/transaction_brokernodes.go
actions/v2/transaction_genesis_hashes.go
grifts/db.go
jobs/job_runner_test.go
jobs/process_unassigned_chunks.go
jobs/process_unassigned_chunks_test.go
models/models_test.go
services/awsgateway/lambda.go
services/iota_wrappers.go
utils/segment_logger.go
utils/trytes_conversion.go
utils/trytes_conversion_test.go

Addressed this issue: https://github.com/oysterprotocol/brokernode/issues/631

Fix build break for brokernode with iota lib upgrade
