broker-node/app/Http/Controllers/UploadSessionController.php
For the beta ip we are sending "https://broker-1.oysternodes.com" (or whatever), so it's trying to make a request on "http://https://broker-1.oysternodes.com"
=> Fix bad request

broker-node/app/Http/Kernel.php, broker-node/composer.json, broker-node/composer.lock, broker-node/config/cors.php
The default config lives in: 
brokernode/broker-node/vendor/barryvdh/laravel-cors/config/cors.php
Our custom config (which is currently the same as the default config) lives in:
brokernode/broker-node/config/cors.php
If we modify those custom configs and expect the changes to actually work, we have to run this:
php artisan vendor:publish --provider="Barryvdh\Cors\ServiceProvider"
=> installing laravel-cors

broker-node/app/Clients/iota-php-port/PrepareTransfers.php
This was a direct port of the iota JS code and was causing memory issues
=> memory problems

broker-node/app/Http/Controllers/UploadSessionController.php
This is so we don't error out, if we send to two brokers.
=> Changes chunk already attached response to success

broker-node/app/ChunkEvents.php, broker-node/app/Clients/BrokerNode.php, broker-node/database/migrations/2018_01_28_155850_create_hook_nodes_table.php, broker-node/database/migrations/2018_02_05_200133_create_chunk_events_table.php
- fixes syntax errors in ChunkEvents that were preventing chunk events recording from working
- updates BrokerNode file so that we no longer include 'http://' and ':250/HookListener.php' at the end of our hooknode ids in the databases
- adds a primary and unique key to the chunk events table to allow easy deleting with phpmyadmin
=> Rfornea patch chunk events

broker-node/database/migrations/2018_01_09_020333_create_data_maps_table.php
So that the most important columns will show up first in phpmyadmin rather than having to manually change the order of the columns every time.
=> Re-ordering these columns

.gitignore, broker-node/app/Clients/BrokerNode.php, broker-node/app/Console/Commands/CheckChunkStatus.php, broker-node/app/Console/Commands/GetFreshTips.php, broker-node/app/Console/Kernel.php, broker-node/app/HookNode.php
-adds a getBroadcastingNodes method to HookNode.  Selects hooknodes similar to getNextReadyNode but with a lower score weight.  Does not update 'contacted_at' because we don't want the hooknodes to miss their chance of increasing their score just because they did a broadcast 
-passes that array of hooknodes to the hooknode who will perform attachToTangle.
-disables the TipSelection service.  It seems to be doing more harm than good.  It's slowing the broker down a lot, and the new changes to iota seem to be resulting in better tips.  
-in the cron job, only re-send chunks in batches of 10.
=> Testnet a patches

README.md, actions/app.go, jobs/flush_old_webnodes.go, jobs/job_runner.go, jobs/job_runner_test.go, jobs/process_unassigned_chunks.go, jobs/update_unverified_data_maps.go, jobs/update_unverified_data_maps_test.go, jobs/verify_data_maps.go, main.go, migrations/20180324202928_create_chunk_channels.down.fizz, migrations/20180324202928_create_chunk_channels.up.fizz, models/chunk_channels.go, models/chunk_channels_test.go, services/iota_wrappers.go
-Job runner is running jobs on the intervals specified, then requeues them to run again
-Added some more iota methods
-Detect number of cores on startup and make that many channels (minus 1)
-Pull unassigned chunks from data_maps in processUnassignedChunks task
-Assign chunks to a "ready" channel that does the PoW  
Currently there's no tracking yet of avg time per chunk, ergo no altering or resetting of "est_ready_time"  
Trying to design this in such a way that it's simple to slip in the hooknodes when we're ready to bring them back.
=> Job runner

actions/upload_sessions.go, jobs/confirm_data_maps.go, jobs/confirm_data_maps_test.go, jobs/job_runner.go, jobs/process_paid_sessions.go, jobs/process_paid_sessions_test.go, jobs/process_unassigned_chunks.go, jobs/verify_data_maps.go, jobs/verify_data_maps_test.go, migrations/.gitignore, migrations/20180313231024_create_data_maps.up.fizz, migrations/20180316183149_create_upload_sessions.up.fizz, migrations/20180320145525_create_completed_data_maps.up.fizz, models/completed_data_maps.go, models/data_maps.go, models/data_maps_test.go, models/upload_sessions.go, models/upload_sessions_test.go, services/iota_wrappers.go, utils/cryptography.go, utils/cryptography_test.go
This PR adds the following:
-a cron job to process paid sessions.  This task makes the PRL payloads in the "message" field and marks all data maps as 'unassigned' if they have paid and their PRLs are buried, which means the process_unassigned_data_maps task will pick them up for processing
-there was a potentially issue with data maps that didn't match the tangle as of verify_data_maps being reassigned a status of "Unassigned", whereupon the process_unassigned_datamaps would promptly do the verification again.  So instead making use of the "Error" status for data maps that don't make the tangle, so when we come across such a status, we won't attempt to (re)verify that it matches the tangle.  We'll just automatically process it and mark it as "Unverified" whereupon it will eventually get …
=> Process paid sessions

jobs/process_paid_sessions.go, jobs/process_paid_sessions_test.go
-Expects a TreasureIdxMap that looks like this:
`[{
"sector": 1,
"idx": 155,
"key": "firstKeySecondMap"
},
{ 
"sector": 2,
"idx": 204,
"key": "secondKeySecondMap"
},
{
"sector": 3,
"idx": 599,
"key": "thirdKeySecondMap"
}]`
-Checks for sessions which have been paid but in which treasure has not been buried, and buries the treasure
-Checks for sessions which have been paid and have treasure buried and marks them as Unassigned so that process_unassigned_chunks will pick them up
-Deletes keys when we are done with them
-Unit tests for all of the above
Wound up writing the method in a way that didn't rely on "Where In" working correctly, wish I'd done that from the start.
=> Process paid sessions 2

.gitignore, .travis.yml, jobs/job_runner.go, jobs/job_runner_test.go, jobs/process_unassigned_chunks.go, jobs/process_unassigned_chunks_test.go, main.go, models/data_maps.go, models/data_maps_test.go, models/upload_sessions.go, models/upload_sessions_test.go, services/iota_wrappers.go
Sorry this is so big.  
The "meat and potatoes" of this PR is that it makes the following changes to process_unassigned_chunks:
-When we have available channels, get sessions in order from oldest to newest.  
-For each session, get its unassigned chunks, ordering the chunks according to alpha (asc) or beta (desc) session type.  Only get as many chunks as we can use at a time for the channels we have.
-Assign the chunks to the channels.  
Long-term we want to do something more sophisticated where we will equally distribute the broker's processing power across different data maps, and I started attempting something like that.  Ran into an issue with a flaky test so have commented that code out for now to revisit after mainnet. 
Also included:
-a call to StoreTransactions, the lack of which …
=> Processing priority

actions/app.go, actions/upload_sessions.go, actions/upload_sessions_test.go, models/models.go, models/upload_sessions.go
Currently, when the ID does not exist we return the error straight from the database. I was having trouble wiring up a custom, more user friendly, error. @rfornea could probably elaborate better than I could on this.
=> Added get response for upload_sessions and tests

actions/upload_sessions.go, jobs/process_paid_sessions_test.go, jobs/update_timed_out_data_maps.go, jobs/verify_data_maps.go, models/models_test.go, models/upload_sessions.go, models/upload_sessions_test.go, utils/mode.go, utils/segment_logger.go, utils/utils.go, utils/utils_test.go
-Can bury a dummy treasure if broker is in TEST_MODE_DUMMY_TREASURE
-Sets broker to PROD_MODE while test suites are being run
-Enables Segment logging
-Changes the treasure statuses to make them more clear
-Updates the TreasureIdxMaps to store the following properties for each entry in the array:  Sector, Idx, Key
=> Can bury dummy treasures

models/data_maps.go, models/data_maps_test.go
This is used in v2/treasure/.
The brokernode will on the fly generate the hash and verify them on the IOTA to make sure this is inserted correctly.
=> Add ComputeSectorHashes method to compute a list of hashes from genHash

models/data_maps.go, models/data_maps_test.go, utils/cryptography.go, utils/cryptography_test.go
-Remove salt
-Remove iv
-Use sha256 hash as the nonce.  Have to trim it according to GCM's nonce size
-Use sha3-256 instead of sha512 hashes as the keys
-Remove deriveKey method and just use the key we tell it to
-Add tests for encryption and decryption methods, we can also use these test vectors if we write encryption/decryption tests on the webnode
-Update CreateTreasurePayload method
-Encrypt and Decrypt methods now return []bytes
-Panic on every single error
=> Better encryption

jobs/job_runner.go, services/iota_wrappers.go, services/iota_wrappers_test.go
The PoW is so fast now that the broker just sits there doing nothing between process_unassigned_chunks runs.  
This PR:
-increases the bundle size so that every PoW process on the broker will take a little longer.  About 3 seconds with this bundle size.
-configures process_unassigned_chunks frequency to change dynamically according to how quick PoW usually is.  We can freely change BundleSize and the frequency the task gets ran will automagically adjust.
=> process_unassigned_chunks frequency changes dynamically

jobs/process_paid_sessions.go, jobs/process_unassigned_chunks.go, jobs/verify_data_maps.go, models/data_maps.go, models/data_maps_test.go, services/iota_wrappers.go, utils/utils.go
-adds a prefix to all treasure chunks, webnode will use this during decryption
-improves segment logging in a few places
-add logic to prevent certain code from running if there's no need for it
-makes sure treasure chunk can never be chunk 0
=> Adds treasure prefix, other small fixes

actions/treasures.go, actions/treasures_test.go, services/eth_gateway.go, services/eth_gateway_test.go, utils/cryptography.go
-add method to eth_gateway to generate an address from a private key
-updates treasures.go and treasures_test.go to reflect that we no longer need to send the ethAddr from the webnode
-removes handling of an error that really isn't an error
=> generate eth address from private key

actions/upload_sessions.go, jobs/claim_unused_prls_test.go, jobs/process_paid_sessions.go, jobs/process_paid_sessions_test.go, jobs/purge_completed_sessions_test.go, models/data_maps.go, models/data_maps_test.go, models/upload_sessions.go, models/upload_sessions_test.go, services/eth_gateway.go
-encrypts the eth keys so we aren't just storing them naked in the dbs.  
-for keys and nonces, I'm using hashes of the session ID and hashes of the CreatedAt time for sessions (if encrypting an ethKey for a session) or for chunks (if encrypting eth keys for treasures)
-buffalo suggests using c.Error instead of c.Render for errors
FYI, this PR means that we'll have to decrypt the eth key of the session to be able to use it for transactions.  But there's a method for that.
=> Encrypt Eth Keys instead of storing naked keys

services/eth_gateway.go
I got this error recently:  
```
--- FAIL: Test_generateEthAddrFromPrivateKey (0.00s)
panic: hex number with leading zero digits [recovered]
panic: hex number with leading zero digits
goroutine 70 [running]:
testing.tRunner.func1(0xc4203540f0)
/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0xa3d560, 0x1116d50)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/ethereum/go-ethereum/common/hexutil.MustDecodeBig(0xc42021e5a0, 0x42, 0x2)
/go/src/github.com/ethereum/go-ethereum/common/hexutil/hexutil.go:172 +0x6f
github.com/oysterprotocol/brokernode/services.generateEthAddrFromPrivateKey(0xc420028700, 0x40, 0x0, 0x0, 0x0)
/go/src/github.com/oysterprotocol/brokernode/services/eth_gateway.go:155 +0x65
github.com/oysterprotocol/brokernode/services_test.Test_generateEthAddrFromPrivateK …
```
=> Hex cannot have a leading 0

actions/actions_test.go, actions/app.go, actions/treasures.go, actions/upload_sessions.go
Inside package actions, everyone had to share EthWrapper/IotaWrapper. Unfortunately, this is hard to change. As a result, move it to app.go.
Since every test in the same package is run sequentially. We need to reset EthWrapper/IotaWrapper for each test.
=> Move EthWrapper/IotaWrapper into app.go

jobs/claim_unused_prls.go, jobs/claim_unused_prls_test.go, jobs/flush_old_webnodes.go, jobs/job_runner.go, jobs/job_runner_test.go, jobs/process_paid_sessions.go, jobs/process_unassigned_chunks.go, jobs/process_unassigned_chunks_test.go, jobs/purge_completed_sessions.go, jobs/update_timed_out_data_maps.go, jobs/verify_data_maps.go, jobs/verify_data_maps_test.go
* Use oyster_utils.LogIfError method through out this package.
* Clean Setting EthWrapper in individual file. Since method is static export, by call SetEthWrapper() will apply for all other files, while other can't access EthWrapper. Instead, use EthWrapper, ItoaWrapper defined in job_runner.go. And reset it each test. Each Unit test could change these two variable without affecting other tests case.
=> Clean up job_runner directory

services/eth_gateway.go
The claim amount is specified in the smart contract, this will send ETH, which we don't want.
Smart contract code for reference:
https://github.com/oysterprotocol/smartcontract/blob/master/contracts/OysterPearl.sol#L228
=> Don't send ETH when claiming PRLs

jobs/process_unassigned_chunks.go
It has been logged in the caller method. So don't need to log it again.
=> Remove dup raven.Capture

actions/transaction_brokernodes.go, actions/transaction_genesis_hashes.go, actions/upload_sessions.go, jobs/process_unassigned_chunks.go, jobs/process_unassigned_chunks_test.go, migrations/20180316183149_create_upload_sessions.up.fizz, migrations/20180422152102_create_completed_uploads.up.fizz, models/completed_uploads.go, models/data_maps_test.go, models/treasure.go, models/upload_sessions.go, services/eth_gateway_test.go, services/iota_wrappers.go, utils/trytes_conversion.go, utils/trytes_conversion_test.go
-broker can now receive the message as trytes or as a binary string
-instead of casting using giota.Trytes() or giota.Address(), the giota library recommends we use giota.ToAddress() and giota.ToTrytes() which has built-in validity checking
-adds version to upload_sessions and completed uploads
I was going to add it to the data_maps table but thought of some possible issues which I mentioned in the mainnet channel.  
Also was going to add a separate migrations file for this change, something like 20180603543234_add_version_to_sessions.up.fizz or something, but I got complaints when I tried to run migrations this way.  If we can't get away with modifying the existing migration files, I will explore this further.  Let's discuss this before we deploy.
=> Binary encoded strings instead of trytes (merge/deploy with corresponding webinterface review)

.env.test, actions/upload_sessions.go
-Add max number of chunks to .env.test file, to be added to prod broker's .env file.  
-Fail the upload if the file is over the maximum number of chunks.  
Even if the client "lies" about the number of chunks, the upload should still fail, because the broker will not complete the whole data map because it needs an accurate number of chunks to build the data map.
=> Server side limit

models/data_maps_test.go, models/stored_genesis_hashes.go, models/stored_genesis_hashes_test.go
While Edmund was QAing webnode/brokernode interaction, we found some errors.  This PR fixes those errors.  
-gobuffalo seems to have problems with NOT IN (?) queries so I have removed that
-better error messages
-no longer change the genesis hash status to assigned, if it has been assigned to fewer webnodes that WebnodeCountLimit
-for verifying the PoW, we were looking for the genesis hash match in the wrong table.  
-move the query to get the stored genesis hashes to the stored genesis hashes models file.
=> QA webnode/brokernode fixes

grifts/db.go
For QAing webnode/brokernode interaction, we need to be able to reset the stored_genesis_hashes statuses to unassigned and webnode count to 0 so that the webnode can get the hashes.  
To run this, `docker-compose exec app buffalo task db:reset_genesis_hashes`
=> Add a grift to reset the stored genesis hashes

migrations/20180316183149_create_upload_sessions.up.fizz, migrations/20180422152102_create_completed_uploads.up.fizz, migrations/20180611231123_add_version_to_upload_sessions.up.fizz, migrations/20180611231345_add_version_to_completed_uploads.up.fizz
Put the version addition in its own migration file.  Should have done this to begin with.
=> Move version to different migration file

.env.test, jobs/job_runner.go, utils/utils.go, utils/utils_test.go
It does not make sense to have job run in the background during unit test. For unit test for job run, they should manually enable the each test.
This will reduce some sentry.io error
=> Just disable Job run in test

migrations/20180623145457_add_msg_status.down.fizz, migrations/20180623145457_add_msg_status.up.fizz, models/data_maps.go
msgStatus will be represent the status of message. Does brokernode hve it or not. It will enable brokernode to do efficient query such as give me all the dataMaps object where its message is uploaded.
Follow up PR will use this field.
=> Add msgStatus column in DataMaps

grifts/db.go, jobs/bury_treasure_addresses.go, jobs/bury_treasure_addresses_test.go, jobs/claim_unused_prls.go, jobs/claim_unused_prls_test.go, jobs/job_runner.go, migrations/20180611231123_add_version_to_upload_sessions.down.fizz, migrations/20180611231345_add_version_to_completed_uploads.down.fizz, migrations/20180621123456_add_transaction_data_to_treasures.down.fizz, migrations/20180621213452_add_transaction_data_to_completed_uploads.down.fizz, migrations/20180625135525_add_treasure_status_to_stored_genesis_hashes.down.fizz, models/completed_uploads.go, models/completed_uploads_test.go, services/eth_gateway.go, services/eth_gateway_test.go
-adds more grifts which I used to QA the claim_unused_prls task
-QA'd to verify that brokernode successfully goes through this sequence:
1.  Send small amount of gas to the transaction address
2.  Use that gas to retrieve the PRL at the transaction address to the broker's wallet 
3.  If there's some ETH still left in the transaction address, retrieve it to the broker's wallet
-adds more methods needed to accomplish the sequence
-adds unit tests of the new methods
-modifies SendETH method to be used with any "from" address that we have the key for
-adds missing down migration files
=> claim_unused_prls QA completed live on the eth network

services/eth_gateway.go
Sometimes the `generateEthAddr` method produces a 62 character long key instead of 64 characters long.  This breaks things.  It does not appear to be anything we are doing but an issue with the ethereum crypto library.  It very rarely happens so the fix for now is to just check at the end of the method if the private key is not 64 characters long, and if it's not, call the method recursively.
=> Add check at end of generateEthAddr to always result in keys with 64 characters

jobs/bury_treasure_addresses_test.go, jobs/check_alpha_payments_test.go, jobs/claim_unused_prls_test.go, jobs/process_paid_sessions_test.go, jobs/process_unassigned_chunks_test.go, jobs/verify_data_maps_test.go, models/broker_broker_transactions_test.go, models/completed_uploads_test.go, models/data_maps_test.go, models/treasure_test.go, models/upload_sessions_test.go
Use suite.Equal(expected, actual) format in all unit test.
Use suite.Nil(err)
Use suite.False(vErr.HasAny())
Use suite.True(foo) for suite.Equal(true, foo) or suite.False(foo) for suite.False(foo)
=> Clean up Unit test assertion.

actions/upload_sessions.go
Checks an .env variable to see if a dev has set DEPLOY_IN_PROGRESS to true, and if so, reject new uploads while deploy is happening.
=> Do not accept new uploads if a deploy is in progress

actions/app.go, actions/status.go, actions/status_test.go
Adds an endpoint `/api/v2/check-availability` that will return true or false based on whether the brokers's DEPLOY_IN_PROGRESS env var is set to true.  We can add more checks to this method in the future if we need to.
=> add endpoint for checking broker status

migrations/20180313231016_create_add_key_procedure.up.sql, migrations/20180313231017_create_drop_key_procedure.up.sql, migrations/20180313231018_create_add_constraint_procedure.up.sql, migrations/20180313231019_create_drop_constraint_procedure.up.sql, migrations/20180719012044_add_unique_constraint_to_completed_data_map.down.sql, migrations/20180719012044_add_unique_constraint_to_completed_data_map.up.sql
-adds genesis hash and chunk_idx as a combined unique index on completed_data_maps to stop duplicates getting into the database.
=> Adds genesis_hash and chunk_idx as unique indexes on completed_data_maps

actions/upload_sessions.go, jobs/purge_completed_sessions.go, models/completed_data_maps.go, models/data_maps.go, services/kv_store.go, services/kv_store_test.go, utils/trytes_conversion.go, utils/utils.go
-adds new methods and tests for KV store
This does not yet implement moving all of data_maps out of SQL.  This just adds new methods to KVStore, and unit tests.  May need to make small changes to these methods with next PR but this should be the bulk of the changes to the kv_store file, aside from pulling out old methods later.
=> Enable KV Store to Create New DB with Each New Upload Session

services/eth_gateway.go
Completes the check-lock-check pattern. Avoids instantiating the singleton more than once.
=> Fixes potential race condition

jobs/process_unassigned_chunks_test.go, jobs/purge_completed_sessions.go, jobs/purge_completed_sessions_test.go, jobs/verify_data_maps.go, jobs/verify_data_maps_test.go, models/upload_sessions.go, models/upload_sessions_test.go, services/eth_gateway.go
-Changes the order of verification.  Previously verification could occur while a file was still being attached.  This caused some redundant attachments.  Now we will wait until the broker thinks it has already attached all chunks before we bother verifying the attachment, which dramatically cuts down on redundancy.  
-Round robin - changes the method of selecting sessions for chunk processing by selecting the session with the oldest update time rather than the oldest creation time.  Since we are constantly updating sessions with a new `NextIdxToAttach` value, the `updated_at` times for sessions will always be changing and every session will periodically be the oldest session (in terms of `updated_at` time).  This means all active sessions will get some attention instead of just the …
=> Add round robining, only verify when all chunks are attached

actions/utils/setup_app.go
See here:https://gobuffalo.io/en/docs/routing#loose-slash
LooseSlash option has been removed and it would cause travis build break. Remove this option completely since the new version will by default turn this on.
=> Remove LooseSlash in the buffalo setting

actions/v2/actions.go, actions/v2/actions_test.go, actions/v2/treasures_test.go, actions/v2/upload_sessions.go, actions/v2/upload_sessions_test.go, actions/v3/actions.go, actions/v3/actions_test.go, grifts/db.go, jobs/bury_treasure_addresses.go, jobs/bury_treasure_addresses_test.go, jobs/check_alpha_payments.go, jobs/check_alpha_payments_test.go, jobs/check_beta_payments.go, jobs/check_beta_payments_test.go, jobs/claim_treasure_for_webnode.go, jobs/claim_treasure_for_webnode_test.go, jobs/claim_unused_prls.go, jobs/claim_unused_prls_test.go, jobs/job_runner.go, jobs/job_runner_test.go, jobs/remove_unpaid_upload_session.go, jobs/remove_unpaid_upload_session_test.go, models/treasure_test.go, models/webnode_treasure_claims_test.go, utils/eth_gateway/eth_gateway.go, utils/eth_gateway/eth_gateway_mock.go, utils/eth_gateway/eth_gateway_test.go, utils/eth_gateway/oysterpearl.go, utils/eth_gateway/pearlDistribute.go
As part of the backend rev2 changes, I'm going to need to pull eth_gateway out of services.  This is because I'll need to import something from services into models, but services already imports models, so that won't work.  
The backend rev2 changes are getting pretty large so I'm going to try to break them into smaller pieces if possible.  This is one of the PRs for that.
=> Moves eth_gateway into utils and change all imports

jobs/attach_treasure.go, jobs/attach_treasure_test.go, jobs/bury_treasure_addresses.go, jobs/bury_treasure_addresses_test.go, jobs/job_runner_test.go, models/treasure.go, models/treasure_test.go, services/iota_wrappers.go, services/prometheus.go
-adds attach_treasure job and tests but does not yet add it to the job runner
-only purge a treasure in bury_treasure_addresses if we have attached and verified it
-add methods to treasures.go to get treasures by signed_status or by genesis hash + index.  Also adds tests.
=> Add attach_treasure job, add methods to treasures.go, update bury_treasure_addresses
